### ISSUE TITLE
Save form progress

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#28] opened 2024-01-26 04:37 UTC
As a SRL, I would like to save my progress on a long form, so I may come back later and complete it when I have more time or all the necessary information.

Acceptance criteria:

- [ ] Client-side only or URL-based solutions are considered
- [ ] Login.gov identity provider added
- [ ] A user session is introduced
- [ ] A method of continuing a prior form is added to the interface

**Comment by JennyRichards-Flexion** [comment] 2024-09-06 16:22
9/6/24: After conversation with Jim, closing this item as a duplicate of one already in review. 
[](https://github.com/GSA-TTS/atj-platform/issues/247)

**Closed by JennyRichards-Flexion** 2024-09-06 16:22 UTC
